#########################################################################
# Title:            Sandbox: Aria2 + AriaNG webui                       #
# Author(s):        JigSawFr                                            #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
# Repository: https://github.com/hurlenko/aria2-ariang-docker
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

# - name: "Generate Secret Key for RPC"
#   ansible.builtin.shell: "openssl rand -hex 20"
#   register: aria2_ng_secret_key

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Pre-Install | Get next available port within the range of '57881-57999' # noqa fqcn[action]
  find_next_open_port:
    low_bound: 57881
    high_bound: 57999
  register: port_lookup_57881
  ignore_errors: true
  
- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Print Tweaking Info
  ansible.builtin.debug:
    msg: "For custom docker envs, please visit: https://github.com/hurlenko/aria2-ariang-docker"
