#########################################################################
# Title:         Sandbox: Settings | Finish                             #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Finish | Check 'settings-updater.py' for new settings"
  ansible.builtin.debug: # noqa jinja[invalid]
    msg:
      - "The 'settings_updater.py' script updated the following
          file{{ 's' if (files_updated_successfully | length > 1) else '' }}: '{{ files_updated_successfully | join(', ') | trim }}'"
      - "Please check {{ 'these files' if (files_updated_successfully | length > 1) else 'this file' }} for the newly added settings"
      - "You can also review the log file: 'settings-updater.log'"
  when:
    - files_updated_successfully | length > 0

# Exit playbook When necessary
- name: Finish | Exit Tasks
  when: exit_is_necessary
  block:
    - name: "Finish | Check 'settings-updater.py' run status for errors"
      ansible.builtin.debug:
        msg:
          - "The 'settings_updater.py' script exited with an error when updating the following
              file{{ 's' if (files_updated_unsuccessfully | length > 1) else '' }}: '{{ files_updated_unsuccessfully | join(', ') | trim }}'"
          - "Please check 'settings-updater.log' for details"
      when: files_updated_unsuccessfully | length > 0

    - name: "Finish | Exit so that user can check updated config files"
      ansible.builtin.debug:
        msg: "Sandbox Installer will now exit."

    - name: "Finish | Exit"
      ansible.builtin.meta: end_play
