#########################################################################
# Title:         Sandbox: Settings | Migrator                           #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Migrator | Migrations for all config files
  block:
    - name: Migrator | All | Migration 01
      ansible.builtin.include_tasks: "migrator/all/migration_01.yml"
