#########################################################################
# Title:         Sandbox: Settings | Start                              #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Start | Install yyq"
  ansible.builtin.include_role:
    name: yyq

- name: "Start | Get 'sandbox.yml' info"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/sandbox.yml"
  register: sandbox_yml

- name: "Start | Create list of config files"
  ansible.builtin.set_fact:
    config_files:
      - "settings.yml"

- name: Start | Initialize vars with empty lists
  ansible.builtin.set_fact:
    files_updated_successfully: []
    files_updated_unsuccessfully: []
    exit_is_necessary: false

- name: "Start | Check if 'settings-updater.log' exists"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/settings-updater.log"
  register: settings_updater_log

- name: "Start | Reset ownership of 'settings-updater.log'"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/settings-updater.log"
    state: file
    owner: "{{ sandbox_yml.stat.uid }}"
    group: "{{ sandbox_yml.stat.gid }}"
    mode: "0664"
  when: (settings_updater_log.stat.exists)
